### PR TITLE
feat: add location on map

### PR DESCRIPTION
**Pull request by dandpz**
- Add company location to data
- Add Map layer with leaflet

### CODE REVIEW

**Comment by FabrizioCafolla** [comment]
@dandpz What field needs to be added in the `data/` files to create the location on the map?

**Comment by dandpz** [comment]
> @dandpz What field needs to be added in the `data/` files to create the location on the map?

'geometry' geopoint format field

**Comment by FabrizioCafolla** [comment]
> > @dandpz What field needs to be added in the `data/` files to create the location on the map?
> 
> 'geometry' geopoint format field

Is there a way to retrieve the coordinates from the address?
Because in the files I add the address field and automatically when it renders the file it creates the geometric point

**Comment by dandpz** [comment]
> > > @dandpz What field needs to be added in the `data/` files to create the location on the map?
> > 
> > 'geometry' geopoint format field
> 
> Is there a way to retrieve the coordinates from the address?
> Because in the files I add the address field and automatically when it renders the file it creates the geometric point

Maybe we could use Google maps API to get coordinates

**Comment by FabrizioCafolla** [comment]
> Maybe we could use Google maps API to get coordinates

I find this https://towardsdatascience.com/geocode-with-python-161ec1e62b89

**Pull request closed without merging**
